services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    env_file:
      - .env
  postgres:
    build: ./database
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 50s
      retries: 5
  client:
      build: ./client
      ports:
        - "5173:5173"
      environment:
        - VITE_API_URL=http://localhost:3000
      command: npm run dev
      depends_on:
        - server
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server
volumes:
  postgres_data:
    driver: local