// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.internals.dbMigrations;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(MessengerDBContext))]
    [Migration("20241004170846_WhoCaresForThisShite")]
    partial class WhoCaresForThisShite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.internals.dbMigrations.tables.Chat", b =>
                {
                    b.Property<int>("ChatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatID"));

                    b.Property<string>("ChatName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ChatID");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.ChatToUser", b =>
                {
                    b.Property<int>("ChatID")
                        .HasColumnType("integer");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ChatID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ChatToUser");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageID"));

                    b.Property<int>("ChatID")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsRedirect")
                        .HasColumnType("boolean");

                    b.Property<long>("SendTime")
                        .HasColumnType("BigInt");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("MessageID");

                    b.HasIndex("ChatID");

                    b.HasIndex("UserID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.ProfilePicture", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Base64EncodedImage")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.HasKey("UserID");

                    b.ToTable("ProfilePictures");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.Token", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("BigInt");

                    b.Property<string>("JWToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.ChatToUser", b =>
                {
                    b.HasOne("server.internals.dbMigrations.tables.Chat", "Chat")
                        .WithMany("ChatsToUsers")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.internals.dbMigrations.tables.User", "User")
                        .WithMany("ChatsToUsers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.Message", b =>
                {
                    b.HasOne("server.internals.dbMigrations.tables.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.internals.dbMigrations.tables.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.ProfilePicture", b =>
                {
                    b.HasOne("server.internals.dbMigrations.tables.User", "User")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("server.internals.dbMigrations.tables.ProfilePicture", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.Token", b =>
                {
                    b.HasOne("server.internals.dbMigrations.tables.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("server.internals.dbMigrations.tables.Token", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.Chat", b =>
                {
                    b.Navigation("ChatsToUsers");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("server.internals.dbMigrations.tables.User", b =>
                {
                    b.Navigation("ChatsToUsers");

                    b.Navigation("Messages");

                    b.Navigation("ProfilePicture")
                        .IsRequired();

                    b.Navigation("Token")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
