// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ChatID   uuid.UUID
	Chatname string
}

type Chatstouser struct {
	UserID uuid.UUID
	ChatID uuid.UUID
}

type Message struct {
	MessageID uuid.UUID
	Content   string
	SendTime  pgtype.Timestamp
	ChatID    uuid.UUID
	UserID    uuid.UUID
}

type Profilepicture struct {
	UserID             uuid.UUID
	Base64EncodedImage string
}

type Token struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

type User struct {
	UserID   uuid.UUID
	Username string
	Email    string
	Password string
}

type Watchedby struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
}
