// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToChat(ctx context.Context, arg AddUserToChatParams) error
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChat(ctx context.Context, chatID uuid.UUID) error
	DeleteUserFromChat(ctx context.Context, arg DeleteUserFromChatParams) error
	GetChatByChatID(ctx context.Context, chatID uuid.UUID) (Chat, error)
	GetChatsOfUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	GetProfilePicture(ctx context.Context, userID uuid.UUID) (Profilepicture, error)
	GetTokenOfUser(ctx context.Context, userID uuid.UUID) (Token, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByToken(ctx context.Context, token string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []int32) ([]User, error)
	GetUsersFromChat(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error)
	SetProfilePicture(ctx context.Context, arg SetProfilePictureParams) error
	SetTokenForUser(ctx context.Context, arg SetTokenForUserParams) (Token, error)
}

var _ Querier = (*Queries)(nil)
